version: "3"

services:
  backend:
    container_name: fullbackend
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27018:27017"